version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_pass
      POSTGRES_DB: ticketing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketnet

  backend:
    build: ./backend
    container_name: backend-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://ticket_user:ticket_pass@postgres:5432/ticketing
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    networks:
      - ticketnet

  frontend:
    build: ./frontend
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - ticketnet
    environment:
      # ðŸ‘‡ Point frontend to backend using host's public IP
      REACT_APP_API_URL: http://13.127.193.57:8000

  admin:
    build: ./admin
    container_name: admin-app
    depends_on:
      - backend
    ports:
      - "3001:80"
    networks:
      - ticketnet
    environment:
      # ðŸ‘‡ Point admin frontend to backend using host's public IP
      REACT_APP_API_URL: http://13.127.193.57:8000

volumes:
  postgres_data:

networks:
  ticketnet:
    driver: bridge
